name: Trust Certification Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  validate-ledger:
    runs-on: ubuntu-latest
    name: Validate Trust Ledger
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Validate JSON Ledger
      run: |
        echo "Validating ledger.json structure..."
        if ! jq empty ledger.json 2>/dev/null; then
          echo "ERROR: ledger.json is not valid JSON"
          exit 1
        fi
        echo "✓ ledger.json is valid JSON"
        
    - name: Verify Trust Documents
      run: |
        echo "Verifying required trust documents exist..."
        files=("README.md" "trust-declaration.md" "definitions.md" "ledger.json")
        for file in "${files[@]}"; do
          if [ ! -f "$file" ]; then
            echo "ERROR: Required file $file not found"
            exit 1
          fi
          echo "✓ $file exists"
        done
        
    - name: Check Directory Structure
      run: |
        echo "Verifying directory structure..."
        dirs=("notices" "promissory-notes")
        for dir in "${dirs[@]}"; do
          if [ ! -d "$dir" ]; then
            echo "ERROR: Required directory $dir not found"
            exit 1
          fi
          echo "✓ $dir directory exists"
        done
        
    - name: Certification Report
      run: |
        echo "════════════════════════════════════════════════════════"
        echo "TRUST CERTIFICATION VALIDATION REPORT"
        echo "════════════════════════════════════════════════════════"
        echo "Trust: The Travis Ryle Private Bank Estate & Trust"
        echo "Date: $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
        echo "Commit: $GITHUB_SHA"
        echo "────────────────────────────────────────────────────────"
        echo "✓ All trust documents validated"
        echo "✓ Ledger structure verified"
        echo "✓ Repository structure confirmed"
        echo "════════════════════════════════════════════════════════"
        echo "This automated certification confirms the integrity of"
        echo "trust records as of this commit."
        echo "════════════════════════════════════════════════════════"
